spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///sys?serverTimezone=UTC
    username: root
    password: ZM1621214417_ace
    druid:
      aop-patterns: com.like4u.papermanager
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false