server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///ssm?serverTimezone=UTC
    username: root
    password: 123456
    druid:
      aop-patterns: com.like4u.papermanager
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 47.98.249.203
    port: 6379
    password: 123321
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com/like4u/papermanager/pojo

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30








