server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: pro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///ssm?serverTimezone=UTC
    username: root
    password: 123456
    druid:
      aop-patterns: com.like4u.papermanager
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 47.98.249.203
    port: 6379
    password: 123321
    database: 1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mail:
    host: smtp.qq.com
    port: 465
    username: dingzhen2001@qq.com
    password: nyfweubxduhfbcbf
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

logging:
  file:
    path: /logs

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com/like4u/papermanager/pojo

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
  #单用户登录 不允许重复登录true  允许重复登录 false
  soloLogin: true



knife4j:
  enable: true
  openapi:
    title: 论文管理系统
    description: 这是一份用于管理后台的接口文档
    email: 15563451092@163.com
    concat: exception
    url: https://127.0.0.1:8090/doc.html
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/







